services:
  - type: web
    name: ai-detection-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Detection.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9.18"
